### ISSUE TITLE
AWS BYOL? 

### ISSUE THREAD

**Issue by davidem** [fortinet/fortigate-terraform-deploy#10]
Good morning, 

are the AWS templates only for PAYG setups? If so, what should I do to add BYOL functionality? The Cloudformation templates have an s3 bucket with lic-files and endpoint and pass this information on as UserData to the fortigate. 

I assume an S3 bucket is not required with Terraform, but how to insert the license(file)? 

Cheers,

David

**Comment by mobilesuitzero** [comment]
Hi,

Currently, AWS terraform scripts are PAYG at the moment.  

BYOL will be added in the future releases.


Cheers

**Comment by Joel-Cripps** [comment]
BYOL has been added see : https://github.com/fortinet/fortigate-terraform-deploy/tree/main/aws/6.4/ha
