### ISSUE TITLE
AliCloud 7.0 - Single VM issue. PAYG not matched with InstanceType

### ISSUE THREAD

**Issue by juwk168** [fortinet/fortigate-terraform-deploy#118]
Hi,

Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_instance.go:480: Resource alicloud_instance RunInstances Failed!!! 
[SDK alibaba-cloud-sdk-go ERROR]:
│ SDK.ServerError
│ ErrorCode: InvalidParameter.NotMatch
│ Recommend: https://next.api.aliyun.com/troubleshoot?q=InvalidParameter.NotMatch&product=Ecs
│ RequestId: BD7FF8F3-1B58-3EC4-B0EE-5AF627947926
│ Message: the provided 'InstanceType -> cpu: 2' and 'Image -> cpu: [8 8]' are not matched.
│
│   with alicloud_instance.Fortigate,
│   on main.tf line 107, in resource "alicloud_instance" "Fortigate":
│  107: resource "alicloud_instance" "Fortigate" {
│

**Comment by mobilesuitzero** [comment]
Hi jukw168,

You would need to adjust the instance type and cpu in the variables to match the ones that are supported for PAYG type.

https://marketplace.alibabacloud.com/products/56700005/sgcmjj00024918.html


Cheers
