### ISSUE TITLE
AliCloud "RAMRoleName" does not exist ???

### ISSUE THREAD

**Issue by juwk168** [fortinet/fortigate-terraform-deploy#119]
Hi,

╷
│ Error: [ERROR] terraform-provider-alicloud/alicloud/resource_alicloud_instance.go:480: Resource alicloud_instance RunInstances Failed!!! [SDK alibaba-cloud-sdk-go ERROR]:
│ SDK.ServerError
│ ErrorCode: InvalidRamRole.NotFound
│ Recommend: https://next.api.aliyun.com/troubleshoot?q=InvalidRamRole.NotFound&product=Ecs
│ RequestId: BD5C6764-0244-3D6C-9CD8-7F92FD5D684B
│ Message: The specified parameter "RAMRoleName" does not exist.
│
│   with alicloud_instance.Fortigate2,
│   on main.tf line 220, in resource "alicloud_instance" "Fortigate2":
│  220: resource "alicloud_instance" "Fortigate2" {

**Comment by mobilesuitzero** [comment]
Hi jukw168,

You would need to create a IAM Role first on alicloud and the put that name in the variables.
variable "iam" {
  default = "<IAM ROLE>"   <--- put your iam ram here.
}

Hope that helps.


Cheers
