### ISSUE TITLE
Oracle OCI cloud => Terrafrom with parameter , fingerprint & private_key_path ? How to find it ?

### ISSUE THREAD

**Issue by juwk168** [fortinet/fortigate-terraform-deploy#121]
Hi, Terraform Guru

https://github.com/fortinet/fortigate-terraform-deploy/blob/main/oci/7.2/ha/terraform.tfvars.example

Is any good to retrieve the fingerprint & private_key_path in OCI console. I try to access it by using 
Identity=> Federation => Identity Provider Details=> Users => User Details under Resource should have the API but not able to get it in OCI console. Any good command to retrieve fingerprint & private_key_path ?? Thanks.

"// Change to your own variables
tenancy_ocid     = ""ocid1.tenancy.oc1..aaaaaaaambr3uzztoyhweohbzqqdo775h7d3t54zpmzkp4b2cf35vs55ck3a""
compartment_ocid = ""ocid1.compartment.oc1..aaaaaaaadftsplqvrt2e63vvfgu4zalufpu4e5b2lfsfnr4p7nv72sz6umqq""
user_ocid        = ""8f57478b49da4f91b40944f698e24d92""
fingerprint      = ""<Fingerprint>""
private_key_path = ""<Private key>""
region           = ""ap-singapore-1"""

**Comment by mobilesuitzero** [comment]
Hi,

Can check at here for the private key and finger print.

Can check out this two urls.
https://docs.oracle.com/en-us/iaas/Content/API/Concepts/apisigningkey.htm
https://docs.oracle.com/en-us/iaas/Content/API/SDKDocs/terraformproviderconfiguration.htm#configuring_the_terraform_provider

Hope that helps. 

Cheers
