### ISSUE TITLE
AWS Loadbalancer Config

### ISSUE THREAD

**Issue by galvanize-brandon-moseley** [fortinet/fortigate-terraform-deploy#130]
The documentation that links to the loadbalancer code is labeled as an active-active configuration, but the code implies active-passive. Is this a miscommunication?

**Comment by mobilesuitzero** [comment]
Hi,

The config used in the loadbalancer is using autoscale. 

config system auto-scale
set status enable
set role primary
set sync-interface port1
set psksecret ${presharekey}
end

Hence, in this case, it's using active-active setup.  If it's active-passive then it will have config sys ha configuration.

Cheers

**Comment by galvanize-brandon-moseley** [comment]
The terraform implies there are active and passive instances and the config also has
set role primary and set role secondary.
