### ISSUE TITLE
Availability of GCP image 7.2.4

### ISSUE THREAD

**Issue by philip-harvey** [fortinet/fortigate-terraform-deploy#133]
The latest image for GCP is 7.2.4 but the repo is using 7.2.3.  Is image 7.2.4 available at?
projects/fortigcp-project-001/global/images/
If so can you please either provide the link or allow compute.images.list to this project

**Comment by Joel-Cripps** [comment]
Looks like listing images works from my personal account. Think these should be what you need:

```
joel_cripps@cloudshell:~ (openconfig)$ gcloud compute images list --project fortigcp-project-001 --filter 724

NAME: fortinet-fgt-724-20230201-001-w-license
PROJECT: fortigcp-project-001
FAMILY: fortigate-72-byol
DEPRECATED:
STATUS: READY

NAME: fortinet-fgtondemand-724-20230201-001-w-license
PROJECT: fortigcp-project-001
FAMILY: fortigate-72-payg
DEPRECATED:
STATUS: READY

```

**Comment by philip-harvey** [comment]
Thanks @Joel-Cripps 
I confirm I can list the images using gcloud, it doesn't work in the console which is how I previously tried but that is probably a console bug.
