### ISSUE TITLE
Question on google_compute_forwarding_rule in /7.2/ha-cross-zone-3-ports/main.tf

### ISSUE THREAD

**Issue by philip-harvey** [fortinet/fortigate-terraform-deploy#136]
The docs say the forwarding rule will fail over to the passive instance if the active instance is unavailable, but unless I'm missing something it looks like it just forwards all traffic to the first instance (google_compute_instance.default.id) 
Am I missing something, or is this a bug?  I'm also curious as to why this setup has the forwarding rule and all the other HA examples don't have this. Is this superfluous?

**Comment by mobilesuitzero** [comment]
Hi,

Forwarding rules, routes, and public ip will failover to the new active instance during the HA failover.  Hence, that will failed over to the active instance.

This config is also in other ha setup as well.  But not all.  However, user can configure this after in their setup as each environments are different.


Hope that helps.

Cheers
