### ISSUE TITLE
Surprising s3:GetObject on * in the policy for ec2 instance role

### ISSUE THREAD

**Issue by ajoga** [fortinet/fortigate-terraform-deploy#15]
Hello, 

What is the purpose of this permission ? 

https://github.com/fortinet/fortigate-terraform-deploy/blob/59ee5c13ee0a8de5a8364ce1f12b28b4115f08a8/aws/6.4/transitgwy/terraform/fortigate.tf#L213

This reference cookbook doesn't mention that permission : https://docs.fortinet.com/vm/aws/fortigate/6.4/aws-cookbook/6.4.0/229470/deploying-fortigate-vm-active-passive-ha-aws-between-multiple-zones

**Comment by mobilesuitzero** [comment]
Hi,

Thanks for the pointing that out.

Can be removed.  Will update that on the next update.


Thanks.

**Comment by mobilesuitzero** [comment]
fixed
