### ISSUE TITLE
Why isn't there a gwlb-crossaztransit example?

### ISSUE THREAD

**Issue by lplpmc** [fortinet/fortigate-terraform-deploy#150]
Am I missing something? Shouldn't there be an example with transit and crossaz?  I believe the gwlb-transit example does not create the routing tables correctly for multi az.

It's possible I am mistaken, if so please let me know

Thank you,

**Comment by mobilesuitzero** [comment]
Hi,

This one should have gwlb with transit gateway example.

https://github.com/fortinet/fortigate-terraform-deploy/tree/main/aws/7.2/gwlb-transit

As for routing tables, user can always update the routes to suit their environment to their needs.

Hope that helps.


Cheers

**Comment by lplpmc** [comment]
Yes, but the config that its creating is only establishing a gateway loadbalancer endpoint in one AZ only?

**Comment by mobilesuitzero** [comment]
@lplpmc , currently it only has one geneve interface.  

snippet- from readme.

A geneve interface will be created base on port2 during bootstrap and this will be the interface where traffic will received from the Gateway Load Balancer.

If need to add more for other AZ, can do that afterwards.

Cheers
