### ISSUE TITLE
Error creating Image: googleapi: Error 403: Required 'compute.images.create'

### ISSUE THREAD

**Issue by CledersonE** [fortinet/fortigate-terraform-deploy#153]
Hi everyone,

I'm trying to deploy the [single example](https://github.com/fortinet/fortigate-terraform-deploy/tree/main/gcp/7.2/single), but I'm getting the error "Error creating Image: googleapi: Error 403: Required 'compute.images.create' permission for 'projects/fortigcp-project-001/global/images/fgtvmgvnic-image', forbidden"

My doubt is about this permission for the fortigcp-project, it is a public project that I can get the image? How should I have permission there to create the image or am I missing something?

**Comment by mobilesuitzero** [comment]
Hi,

If you are using GVNIC nic type, then you would need to use the public image and then create a local custom image in your project.   And, use that during your deployment.

Or can use VIRTIO_NET in the nic type and that should be able to use the public image for deployment.

Hope that helps.


Cheers

**Comment by mobilesuitzero** [comment]
Hi,

Updated the code to use the full source image instead.  Should work now, please update to the latest.

Thanks.

**Comment by CledersonE** [comment]
It works, thank you very much!
