### ISSUE TITLE
GCP 7.4 single template

### ISSUE THREAD

**Issue by KhalilSecurity** [fortinet/fortigate-terraform-deploy#168]
Few issues I'm facing with 7.4 deployments on GCP:

1. Variable "vpc_cidr" is not used anywhere, and should be removed from the template
![2023-06-23 23_03_32-Code search results · GitHub - Brave](https://github.com/fortinet/fortigate-terraform-deploy/assets/51271290/0b07b869-ce67-481d-8a50-db50aa0745fc)

2. Template is missing the default route in private VPC to point to fortigate instance, you need something like this or similar: **resource "google_compute_route" "defaultrouteprivate" {
    name         = "defaultrouteprivate"
    dest_range   = "0.0.0.0/0"
    network      = google_compute_network.vpc_network2.name
    next_hop_instance = google_compute_instance.default.name
    next_hop_instance_zone = var.zone
    priority     = 0
}**
![2023-06-24 01_10_44-Routes – VPC network – FGT-ElastiCourse – Google Cloud console - Brave](https://github.com/fortinet/fortigate-terraform-deploy/assets/51271290/12f76dc5-35ed-48e3-a55f-f7efa242d349)

3. It's better to define vpc names as public and private instead of using the random string, which could be confusing to new users

**Comment by mobilesuitzero** [comment]
Hi KhalilSecurity,

Thanks for the response.


It will be fixed in.

https://github.com/fortinet/fortigate-terraform-deploy/pull/169


Thanks
