### ISSUE TITLE
How to add a new private subnet and create a dynamic route (GCP)

### ISSUE THREAD

**Issue by CledersonE** [fortinet/fortigate-terraform-deploy#171]
Hello folks,

In the current [HA example](https://github.com/fortinet/fortigate-terraform-deploy/tree/main/gcp/7.4/ha), there is one private subnet in which each FortiGate instance has one nic and one GCP route that FortiGate will change automatically if the primary server fails to route to the second one. I'm wondering if I need to create a second private VPC that will also be private and attach each FortiGate instance with a nic in this new subnet, I'll have to create another route to do the same (change from primary to the secondary), what it the necessary configuration that I need to do on FortiGate to change this new route automatically, is it possible to do that?

Thank you.

**Comment by mobilesuitzero** [comment]
Hi CledersonE,

If adding another route table to failover during the HA failover event.  Then you would need to add the extra route table in the sdn connector configuration.

config system sdn-connector
    edit "gcp"
: 
        config route
            edit <The new route table name that you added from gcp side.>
            next
        end

https://docs.fortinet.com/document/fortigate-public-cloud/7.4.0/gcp-administration-guide/214977/creating-a-gcp-route-table

Hope that helps.


Cheers
