### ISSUE TITLE
Deployment of Azurevwan fails: IPSEC P1 Interface

### ISSUE THREAD

**Issue by gitguitar** [fortinet/fortigate-terraform-deploy#176]
Hello all,

by deloying this
https://github.com/fortinet/fortigate-terraform-deploy/tree/main/azure/7.4/azurevwan

i get this error:

fortios_vpnipsec_phase1interface.vwan1phase1: Creating...
fortios_vpnipsec_phase1interface.vwan2phase1: Creating...
╷
│ Error: Error creating VpnIpsecPhase1Interface resource: Internal Server Error - Internal error when processing the request (500)
│
│   with fortios_vpnipsec_phase1interface.vwan1phase1,
│   on fortigate.tf line 1, in resource "fortios_vpnipsec_phase1interface" "vwan1phase1":
│    1: resource "fortios_vpnipsec_phase1interface" "vwan1phase1" {
│
╵
╷
│ Error: Error creating VpnIpsecPhase1Interface resource: Internal Server Error - Internal error when processing the request (500)
│
│   with fortios_vpnipsec_phase1interface.vwan2phase1,
│   on fortigate.tf line 33, in resource "fortios_vpnipsec_phase1interface" "vwan2phase1":
│   33: resource "fortios_vpnipsec_phase1interface" "vwan2phase1" {
│
╵

I do note something Case Sensitive related (can't tell if this is the issue), yet can anyone assist what's the probleme here?

The mentioned Lines in fortigate.tf remained untouched .
Thank you!

**Comment by mobilesuitzero** [comment]
Hi,

Base on that error, it looks like there is an issue when doing rest api call on the FortiGate 
You can try to turn on the debug on the FortiGate to see why it failed.

diag debug enable
diag debug cli 8
diagnose debug application httpsd -1

And, see why it would fail to create those ipsec interface.


Cheers

**Comment by mobilesuitzero** [comment]
close issue as no updates for a while.
