### ISSUE TITLE
External LB with Backend Service (GCP)

### ISSUE THREAD

**Issue by CledersonE** [fortinet/fortigate-terraform-deploy#177]
I'm trying to change the type of the external load balancer from TCP to L3_DEFAULT to be able to work with [multiple protocols supported by this type of load balancer](https://cloud.google.com/load-balancing/docs/network/networklb-backend-service#forwarding-rule-protocols) and with a backend service rather a target pool, however I'm facing an issue with the health check to work with the external LB and the backend service. I've created a [google_compute_region_health_check](https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/compute_region_health_check) which seems the only one supported for the external load balancer using the same parameters as we have in the template for the health check using the target pool, but for the unmanaged groups (the same unmanaged groups used by the internal LB since this [config is supported](https://cloud.google.com/load-balancing/docs/backend-service#restrictions_and_guidance)), both are unhealthy. I'm wondering if there is any detail from FortiGate instances that I need to do or the probe policy will be the same? Or maybe you faced an issue to use a backend service for the external LB as well, and that's why you're using a target pool? Here are the code and the prints:

`resource "google_compute_forwarding_rule" "default" {
  name       = "external-lb-${random_string.random_name_post.result}"
  region     = var.region
  ip_address = google_compute_address.static.address
  ip_protocol     = "L3_DEFAULT"
  all_ports       = true
  backend_service = google_compute_region_backend_service.external_load_balancer_backend.self_link

}

resource "google_compute_region_backend_service" "external_load_balancer_backend" {
  name                            = "external-slb-backend-${random_string.random_name_post.result}"
  region                          = var.region
  connection_draining_timeout_sec = 10
  session_affinity                = "CLIENT_IP"
  protocol              = "UNSPECIFIED"
  load_balancing_scheme = "EXTERNAL"

  backend {
    group = google_compute_instance_group.umig_active.self_link
  }

  backend {
    group = google_compute_instance_group.umig_passive.self_link
  }

  health_checks = [
    google_compute_region_health_check.hc_ext.self_link
  ]
}

resource "google_compute_region_health_check" "hc_ext" {
  name               = "external-slb-healthcheck-${random_string.random_name_post.result}"
  check_interval_sec = 3
  timeout_sec        = 2
  http_health_check {
    port = "8008"
  }
  log_config {
    enable = true
  }
}`

Prints:
<img width="793" alt="Screenshot 2023-08-22 at 16 30 38" src="https://github.com/fortinet/fortigate-terraform-deploy/assets/42626863/c773978d-5330-4c50-89ba-49a465338e78">
<img width="331" alt="Screenshot 2023-08-22 at 16 30 55" src="https://github.com/fortinet/fortigate-terraform-deploy/assets/42626863/db1d8669-743b-426e-b028-d542077d0311">

**Comment by mobilesuitzero** [comment]
Hi CledersonE,

If you are using different type of load balancer, then you might need to allow the probe traffic through firewall. 

https://cloud.google.com/load-balancing/docs/health-check-concepts

Make sure you have open up on the gcp firewall side for tcp port 8008, and also do a sniffer on the FGT to make sure the probe traffic is arriving on the external port of FGT(port1).


Hope that helps.

Cheers
