### ISSUE TITLE
Possible Typo in Architecture Diagram

### ISSUE THREAD

**Issue by rpattcorner** [fortinet/fortigate-terraform-deploy#18]
Is it possible there's a minor typo in the architecture diagram?  Or am I misunderstanding something after much head scratching?  In the Ingress RTB I see:

![image](https://user-images.githubusercontent.com/1488518/109828135-5c00b700-7c0a-11eb-8df6-e9687db40071.png)

however in the private subnets that the code indicates are the targets of the ingress RTB I see:

![image](https://user-images.githubusercontent.com/1488518/109837974-b6524580-7c13-11eb-810e-2a4dbac5cd87.png)

So, the code (network.tf) says:
![image](https://user-images.githubusercontent.com/1488518/109828545-b8fc6d00-7c0a-11eb-940e-e59a820304d7.png)

Could the private subnets and their RTB CIDRs be mislabeled?

**Comment by mobilesuitzero** [comment]
Hi,

Thanks for noticing it.  It's a typo in the diagram.  

Will update that on the next update.


Thanks.

**Comment by mobilesuitzero** [comment]
fixed on the latest update
