### ISSUE TITLE
Issue with deploying ha-3ports configuration on GCP

### ISSUE THREAD

**Issue by etnarossolab** [fortinet/fortigate-terraform-deploy#183]
When attempting to deploy https://github.com/fortinet/fortigate-terraform-deploy/tree/main/gcp/7.4/ha-3ports,
I get following error and unable to proceed...
Is this a problem with the code or anything wrong in my setup?

$ terraform plan -out myplan.out
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 262, in resource "google_compute_instance" "default2":
│  262:     image      = var.image
│ 
│ An argument named "image" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 267, in resource "google_compute_instance" "default2":
│  267:     image      = var.image
│ 
│ An argument named "image" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 272, in resource "google_compute_instance" "default2":
│  272:     image      = var.image
│ 
│ An argument named "image" is not expected here.

**Comment by mobilesuitzero** [comment]
Hi etnarossolab,

Thanks for the comment.  Fix has been update, please try the latest update and try again.

Cheers
