### ISSUE TITLE
How could I change the configuration of FortinetVM without destroying EC2?

### ISSUE THREAD

**Issue by Theerapong** [fortinet/fortigate-terraform-deploy#19]
Hi, I provisioned FortinetVM via Terraform.  Then, when I changed some configuration inside the file "fgtvm.conf", I found that Terraform will destroy AWS EC2 and create a new EC2 again.

Could I have an option to change the configuration of FortinetVM in the same EC2 VM?

**Comment by Joel-Cripps** [comment]
Changing the cloud-init bootstrap will most likely trigger a rebuild of the VM. These scripts use the aws providers. If you want to use Terraform to change the configs after deployment you should take a look at the FortiOS Terraform provider which is meant for just that: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs#release

We'll have some more code that demonstrates the FortiOS terraform provider soon within the https://github.com/fortinet/demo-extensions repo.

**Comment by Theerapong** [comment]
> Changing the cloud-init bootstrap will most likely trigger a rebuild of the VM. These scripts use the aws providers. If you want to use Terraform to change the configs after deployment you should take a look at the FortiOS Terraform provider which is meant for just that: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs#release
> 
> We'll have some more code that demonstrates the FortiOS terraform provider soon within the https://github.com/fortinet/demo-extensions repo.

💚 Thank you so much 🙏  @Joel-Cripps
