### ISSUE TITLE
Terraform Deploy for FortiGate 6.4

### ISSUE THREAD

**Issue by craigforr** [fortinet/fortigate-terraform-deploy#20]
Is there updated deployment code for FortiGate 6.4 ?

**Comment by mobilesuitzero** [comment]
Hi,

The deployment code for FortiOS 6.4 is already there.  Is there any particular update you are looking for?

Cheers

**Comment by craigforr** [comment]
My apologies.  When I visited the repo prior to opening this issue, `6.2` was the only subdirectory.  It must have either been a display glitch or the changes were only just pushed up.  Either way, between this repository and the Terraform templates under [fortinet/azure-templates](https://github.com/fortinet/azure-templates/tree/main/FortiGate/Terraform), I am all set.

Thank you for the quick reply!

Craig
