### ISSUE TITLE
Error: error creating gateway Load Balancer: DuplicateLoadBalancerName

### ISSUE THREAD

**Issue by sahmed3-cpu** [fortinet/fortigate-terraform-deploy#21]
Hi,

 
[terraform.tfstate.txt](https://github.com/fortinet/fortigate-terraform-deploy/files/6274824/terraform.tfstate.txt)

Running into issue when executing Fortigate Terraform
AWS gwlb solution. Please check the error below. I don't have any prior LB or TG created in the region. 

Any thoughts ?? 

aws_lb.gateway_lb: Creating...
aws_lb_target_group.fgt_target: Creating...

Error: error creating gateway Load Balancer: DuplicateLoadBalancerName: A load balancer with the same name 'gatewaylb' exists, but with different settings
        status code: 400, request id: 45ffa03a-738e-40f6-8bfd-a3b7be89bd5a

  on network.tf line 208, in resource "aws_lb" "gateway_lb":
 208: resource "aws_lb" "gateway_lb" {

Error: error creating LB Target Group: DuplicateTargetGroupName: A target group with the same name 'fgttarget' exists, but with different settings
        status code: 400, request id: d9916dab-014b-4004-9f07-6c3058b0ce79

  on network.tf line 217, in resource "aws_lb_target_group" "fgt_target":
 217: resource "aws_lb_target_group" "fgt_target" {

**Comment by mobilesuitzero** [comment]
Hi,

Please make sure there is no existing load balancer and target group name with the same in the region that you are trying to deployed.


Cheers
