### ISSUE TITLE
terraform fmt - missed some sections of automated formatting.

### ISSUE THREAD

**Issue by robinmordasiewicz** [fortinet/fortigate-terraform-deploy#211]
https://github.com/fortinet/fortigate-terraform-deploy/blob/0def2453c63b46f21d155aa88e47627c49111d28/ibm/7.4/ha/fgt.tf#L73C1-L89C6

In the referenced code there are examples where "terraform fmt" might have made some corrections, but left the sections alone to be manually fixed.

**Comment by mobilesuitzero** [comment]
fixed in 

https://github.com/fortinet/fortigate-terraform-deploy/pull/216
