### ISSUE TITLE
Should not require service account key json

### ISSUE THREAD

**Issue by taoszhanna** [fortinet/fortigate-terraform-deploy#22]
The terraform google provider does not require a service account key, and it is security worst practice to use or distribute downloaded service account key material or rely on it in any way. 
Could we please refactor this TF to either: 
a) run as the current user 
b) run with service account impersonation or ADC
c) use temporary OAUTH

**Comment by mobilesuitzero** [comment]
Hi,

Thanks for your comment.

We will think about how to refactor that on the next release.


Cheers

**Comment by taoszhanna** [comment]
Sure, thanks. Got that from this security blog here:
https://jryancanty.medium.com/stop-downloading-google-cloud-service-account-keys-1811d44a97d9

**Comment by mobilesuitzero** [comment]
Hi,

Issue should be fixed by using oauth2 token in the commit 6a038728e9e37850555b2736086551aa3525312e instead of using the service account json file.

Cheers
