### ISSUE TITLE
Configuration shows up in user data but doesn't apply to the instance

### ISSUE THREAD

**Issue by main-salman** [fortinet/fortigate-terraform-deploy#222]
Hello,

I am running into an issue where the configuration shows up in user data (AWS Console > FW Instance > Action > Instance Setting > Edit user data), but, for some reason, it's not showing up in the fw configuration itself. Can't figure out why.

Thanks.

**Comment by Joel-Cripps** [comment]
On the FortiGate run `diag debug cloudinit show` should give you some info on what's going on.

**Comment by main-salman** [comment]
Thank you for the quick reply. Here's the situation:

- With the license file and the config (which is only 250 lines long), the user_data ends up being 20KB - while AWS has a user_data limit of 16KB
- We need to use BYOL
- I just removed the license file text (left just one line), so the license is no longer valid, to bring the user_data (config + license) back down below 16KB

Thanks to your response, I can see that it's complaining about the license - and I guess it doesn't proceed because of the invalid license. I was thinking that I can put in the valid license in a later step manually (which is much less work than doing 250 lines of config manually ;) )

Here is the output from the `diag debug cloudinit show` command:

`FortiGate-VM64-AWS # diag debug cloudinit show 
 >> Checking metadata source aws
 >> MIME parsed preconfig script
...
 >> MIME parsed preconfig script
 >> MIME parsed VM license
 >> AWS failed to get ssh public key, 404
 >> Run preconfig script
 >> FortiGate-VM64-AWS $  config system globalconfig system vdom-exceptionconfig system dnsconfig system interfaceconfig system interfaceconfig router route-mapconfig router bgp--==AWS==
 >> command parse error before 'globalconfig'
 >> Command fail. Return code 1
 >> Finish running preconfig script
 >> Trying to install vmlicense ...
 >> Cloudinit failed to install license!
 >> --Invalid license-------------------
 >> -----BEGIN FGT VM LICENSE-----
 >> ---------------------
 >> Cloudinit couldn't find any valid license from config drive to install
 >> Config script is not available`

**Comment by mobilesuitzero** [comment]
Hi,

If the user_data is over the limit, then maybe can try use the s3 bucket as bootstrap.

https://docs.fortinet.com/document/fortigate-public-cloud/7.4.0/aws-administration-guide/712355/bootstrapping-the-fortigate-vm-at-initial-bootup-using-user-data

Let see if that would work for you.

Cheers

**Comment by main-salman** [comment]
Thank you - I will try that!

**Comment by main-salman** [comment]
To avoid another variable with S3, I am first going to try without S3. I have simply reduced the config to fit the config and license under 16KB. I think I am running into some weird new line character missing issue or something.

<img width="654" alt="image" src="https://github.com/fortinet/fortigate-terraform-deploy/assets/15636147/5266100f-1779-459c-a3b1-bc19180c3244">

**Comment by main-salman** [comment]
![image](https://github.com/fortinet/fortigate-terraform-deploy/assets/15636147/42008c9f-49ac-4801-8c17-615a8cb6045a)

The firewall configuration is being passed into the firewall instance as a single line - that seems to be the root of the problem. Any ideas why this might be happening?

**Comment by main-salman** [comment]
This is how the above config appears under user data (I added extra line characters for test to see if that makes a difference - it didn't)

<img width="347" alt="image" src="https://github.com/fortinet/fortigate-terraform-deploy/assets/15636147/276cbd40-f163-4105-8701-aa26662694ca">

**Comment by mobilesuitzero** [comment]
close issue as no more updates.
