### ISSUE TITLE
AWS Key Pair 

### ISSUE THREAD

**Issue by mario-nc** [fortinet/fortigate-terraform-deploy#223]
Hello, 

In the [fgtvm.tf](https://github.com/fortinet/fortigate-terraform-deploy/blob/main/aws/7.4/single/fgtvm.tf) file key pair is referred as a variable. 
```
resource "aws_instance" "fgtvm" {
  //it will use region, architect, and license type to decide which ami to use for deployment
  ami               = var.fgtami[var.region][var.arch][var.license_type]
  instance_type     = var.size
  availability_zone = var.az1
  key_name          = var.keyname
  user_data = templatefile("${var.bootstrap-fgtvm}", {
    type         = "${var.license_type}"
    license_file = "${var.license}"
    adminsport   = "${var.adminsport}"
  })
```

What is the point of provisioning Fortigate EC2 instance with key pair? It looks like the public key is not automatically copied to the instance, so after provisioning EC2, logging to the Fortigate using the key-pair is not possible (still password needs to provided). 

Am I missing something?

**Comment by mobilesuitzero** [comment]
Hi,

In the variables.tf, there is a parameter.
//  Existing SSH Key on the AWS
variable "keyname" {
  default = "<AWS SSH KEY>"
}

User suppose to provide the existing keyname in there and can login the fortigate via the ssh key.


Cheers

**Comment by mario-nc** [comment]
Hi

I wasn't able to login with keypair, because I was getting an error: 
`sign_and_send_pubkey: no mutual signature supported` 

Solved with the parameter: `ssh -o PubkeyAcceptedKeyTypes=ssh-rsa -i key.pem admin@ip`
