### ISSUE TITLE
Multi-AZ with only two firewalls?

### ISSUE THREAD

**Issue by lplpmc** [fortinet/fortigate-terraform-deploy#240]
In regards to the example shown in: fortigate-terraform-deploy/aws/7.4/gwlb-crossaz/

How would support for a 3rd or 4th customer AZ be achieved without adding additional firewalls per AZ?

Thanks,

**Comment by mobilesuitzero** [comment]
Hi IpIpmc, 

If you are adding extra AZ, then you would need to add extra firewall in those AZ as well.

Cheers

**Comment by mobilesuitzero** [comment]
close issue as no further updates.
