### ISSUE TITLE
Upgrade Fortigate HA Image Strategy (GCP)

### ISSUE THREAD

**Issue by CledersonE** [fortinet/fortigate-terraform-deploy#254]
Hello,

I'll be deploying Fortigate with HA on GCP for my production environment, and I'm looking for recommendations on how to upgrade Fortigate using IAC tools. From what I can see, probably I'll use Terraform to deploy the environment and then use Ansible to work with all the configurations that I need, however one doubt that I have is when I need to upgrade Fortigate (from 7.4.3 to 7.4.4 for example) what could be a good approach for production? I can see that the Fortigate console has a feature to upgrade, but I'd like to avoid any manual interaction in the console. I tried from this [example](https://github.com/fortinet/fortigate-terraform-deploy/tree/main/gcp/7.4/ha-dualloadbalancer) to create two separated google_compute_image resources so I could pass on each the image version that I want, and then change first on passive template/instance, validate so I could do the switch and upgrade on active, but it didn't work. So I wondering if Terraform is not the best tool to work with upgrades and if you recommend any strategy?

I've read the [GCP Administration Guide](https://docs.fortinet.com/document/fortigate-public-cloud/7.4.0/gcp-administration-guide/736375/about-fortigate-vm-for-gcp) but didn't find anything relevant regarding upgrading versions for Fortigate.

Any recommendation is much appreciated.

Thank you.

**Comment by mobilesuitzero** [comment]
Hi,

To do upgrade of FortiGate, best to do the firmware upgrade via GUI.

https://docs.fortinet.com/document/fortigate/7.4.4/administration-guide/596131/upgrading-individual-devices

Hope that helps.

Cheers

**Comment by mobilesuitzero** [comment]
Hi,

Either approach on the upgrade can work.  Just which one is easier for you.

Cheers
