### ISSUE TITLE
Health Check Probe Responders (GCP)

### ISSUE THREAD

**Issue by CledersonE** [fortinet/fortigate-terraform-deploy#255]
Hello,

Based on the GCP documentation for FortiGate to configure health check probe responders (Through [Web Console](https://docs.fortinet.com/document/fortigate-public-cloud/7.4.0/gcp-administration-guide/84619/configure-health-check-probe-responders) and [GCloud CLI](https://docs.fortinet.com/document/fortigate-public-cloud/7.4.0/gcp-administration-guide/819717/configure-health-check-probe-responders)), the port1 should have `set ip ELB_FRONTEND/32` using the external IP of the load balancer, however looking at the [template provided in this repo](https://github.com/fortinet/fortigate-terraform-deploy/tree/main/gcp/7.4/ha-dualloadbalancer) I don't see this config on port1, it is only set on port2 with the IP of the internal load balancer `set ip ILB_FRONTEND/32`. I'd like to confirm if this is accurate for the template or if it needs to be fixed.

Thank you.

**Comment by mobilesuitzero** [comment]
Hi CledersonE,

For the port1, there is the VIP configuration which is mapped to a loopback IP address in the loopback interface.   So, that part is for the responding of the probe.

Hope that helps.

CHeers
