### ISSUE TITLE
bake-marketplace-agreement-into-iac

### ISSUE THREAD

**Issue by AJLab-GH** [fortinet/fortigate-terraform-deploy#256]
Would it be possible to integrate the marketplace-agreement acceptance into the code, and document in the README that the templates will automatically accept the terms and conditions for the offers used in the deployment?

**Azure Example:**

resource "null_resource" "marketplace_agreement" {
  for_each = local.vm_image

  provisioner "local-exec" {
    command = "az vm image terms accept --publisher ${each.value.publisher} --offer ${each.value.offer} --plan ${each.value.sku}"
  }

  triggers = {
    publisher = each.value.publisher
    offer     = each.value.offer
    sku       = each.value.sku
  }
}

**Comment by mobilesuitzero** [comment]
Hi,

Thanks for the info.  
Will see if can do another approach accepting marketplace terms besides using the azure CLI.


Cheers

**Comment by mobilesuitzero** [comment]
resolved in.

https://github.com/fortinet/fortigate-terraform-deploy/pull/257
