### ISSUE TITLE
cloudinit failure with byol license

### ISSUE THREAD

**Issue by ajlab-gh** [fortinet/fortigate-terraform-deploy#265]
The default aws/7.4/transitgwyconnect/ deployment has a high failure rate due to cloudinit exceeding 16KB limit. This is due to the size of the configuration files, in addition to the license files.

example: aws/7.4/transitgwyconnect/fgtvm.conf + license.lic

**Comment by AJLab-GH** [comment]
Since each FortiGate should receive it's own license file, the variable for license should be changed to a list:

```terraform
// license file for the fgt
variable "licenses" {
  // Change to your own byol license file, license.lic
  type    = list(string)
  default = [ "license1.lic", "license2.lic"]
}
```

```terraform
resource "aws_instance" "fgtvm" {
  //it will use region, architect, and license type to decide which ami to use for deployment
  ami               = var.fgtami[var.region][var.arch][var.license_type]
  instance_type     = var.size
  availability_zone = var.az1
  key_name          = var.keyname
  user_data = jsonencode({
    bucket  = aws_s3_bucket.s3_bucket.id,
    region  = "ca-central-1",
    license = var.licenses[0],
    config = "/fgtvm.conf"
  })
  ```
  
  The second Fortigate should use
  ```terraform
  license = var.licenses[1],

**Comment by AJLab-GH** [comment]
I have created a working example of the transitgwyconnect repo with the following additional resources:
https://github.com/AJLab-GH/transitgwyconnect

aws_iam_role (create role for resource failover, plus s3 access)
aws_s3_bucket (for lic and conf files)
aws_s3_object (pointers to lic and conf files)
aws_vpc_endpoint (so passive can get bootstrap without an eip)

**Comment by mobilesuitzero** [comment]
fixed in pr.

https://github.com/fortinet/fortigate-terraform-deploy/pull/272
