### ISSUE TITLE
Unused Variables on GCP Active/Passive Configuration Template

### ISSUE THREAD

**Issue by fdmsantos** [fortinet/fortigate-terraform-deploy#269]
In GCP/7.6/ha-dualloadbalancer/loadbalance.tf, in the instance template for active (also for passive) fortigate, it's been passing clusterip and internalroute variables in templatefile for active configuration file template.
But in Active configuration file template i don't find reference to these variables.  Should these variables been removed?

**Comment by mobilesuitzero** [comment]
Thanks.

Removed the unused variables.

https://github.com/fortinet/fortigate-terraform-deploy/commit/ffb1157228fdf038ca28314a0c27870c101a3cf1
