### ISSUE TITLE
Configuration not picked up

### ISSUE THREAD

**Issue by mies-itq** [fortinet/fortigate-terraform-deploy#271]
Hello,

We are experiencing issues related to the Fortigate Azure deployment. The configuration file is not being picked up by the Fortigate. How can we debug or validate what is going on?

File in question:
- fgtvm.conf

Code in question:

```hcl
custom_data = templatefile("${var.bootstrap-fgtvm}", {
  type         = var.license_type
  license_file = var.license
  format       = "${var.license_format}"
})
```

Best regards,

M. Buijs

**Comment by Joel-Cripps** [comment]
In your FortiGate run:

`diag debug cloudinit show`

This will give you some debug

**Comment by mobilesuitzero** [comment]
close issue as no further updates
