### ISSUE TITLE
EBS volumes are wrong Type

### ISSUE THREAD

**Issue by jgrammen-agilitypr** [fortinet/fortigate-terraform-deploy#278]
aws/7.4/single/fgtvm.tf

```
  root_block_device {
    volume_type = "standard"
    volume_size = "2"
  }

  ebs_block_device {
    device_name = "/dev/sdb"
    volume_size = "30"
    volume_type = "standard"
  }
  ```
you are setting the volume_type to "standard", but the ami defaults to
![image](https://github.com/user-attachments/assets/0761bdce-c2b1-4281-9293-4fb7a8ab875e)
so you are overriding the ami default gp2 disk type and instead forcing aws "standard" (https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volume-types.html#vol-type-prev ) disks.

It would be even better if this supported attaching a separate aws ebs volume via:

```
resource "aws_ebs_volume" "fortigate_log_disk" {
  availability_zone = local.security_vpc_azs[count.index]
  type = "gp3"
  size = "30"
  tags = merge(local.common_tags, { Name = "fortigate-${local.security_vpc_azs[count.index]}-log-volume" })
  count = var.security_vpc.az_count
}

resource "aws_volume_attachment" "fortigate_log_vol_attach" {
  device_name = "/dev/sdb"
  volume_id   = aws_ebs_volume.fortigate_log_disk[count.index].id
  instance_id = aws_instance.fortigate[count.index].id
  count = var.security_vpc.az_count
}
```
Then the log disk could be managed separatly, resized, changed type, additional io's provision etc without impacting the vm

**Comment by mobilesuitzero** [comment]
changed to gp2.

https://github.com/fortinet/fortigate-terraform-deploy/pull/281
