### ISSUE TITLE
FGT AWS 6.4 -  Image version 6.4.3 not available in AWS 

### ISSUE THREAD

**Issue by liquid-cloud** [fortinet/fortigate-terraform-deploy#32]
Hello, 

FortiOS 6.4.3 image is not available in AWS (Frankfurt eu-central-1), but it is needed according to your Terraform template:

![image](https://user-images.githubusercontent.com/49679701/119824868-a8e8e680-bef6-11eb-8ce3-de75ed36139e.png)

We tried running 6.4.4 and 6.4.5 instead but we are unable to access the firewalls in any way (SSH, Browser, Telnet etc.). We are getting timeout - we checked security policies etc. seems to be a FortiGate configuration issue.

Is the AWS/6.4/ha template up to date and working and what is the correct image that has to be used for Pay as you go license ? 

Thank you

**Comment by mobilesuitzero** [comment]
Hi,

Thanks for the comment.  We will update the AMI to the latest 6.4.5.

As to unable access the instances, we should be able to access instance via either ssh or https via the MGMTPublicIP from the output file.

Outputs:

FGTActiveMGMTPublicIP = <active public ip>
FGTClusterPublicFQDN = <fqdn url>
FGTClusterPublicIP = <cluster public ip>
FGTPassiveMGMTPublicIP = <passive public ip>
Password = <password>
Username = <username>


Please also make sure the allowaccess is enable for the ssh or https for accessing the firewall from the conf file.

edit port4
set alias hamgmt
set mode static
set ip ${port4_ip} ${port4_mask}
set allowaccess ping https ssh fgfm     <------
set mtu-override enable
set mtu 9001
next


Cheers

**Comment by liquid-cloud** [comment]
Hello,

Thank you very much for your reply. I'd like to share some findings:

- We are now trying with another image - ami-0479cc1e690725514 - which is a ONDEMAND image according to its name and we had to accept the terms and condition for the 30 day trial FortiGate AWS Subscription.
- With this image, deploying the AWS 6.4 template produces the same result - We are unable to access the FGT - despite having the exact configuration as you suggested. 
-  Therefore, we removed all config from `config-active.conf `, redeployed and we are able to access the firewalls on port 443. 
-  With this deployment Interfaces are now configured with IPs - DHCP (Dynamically)
- Running the configuration from `config-active.conf` manually line by line in the UI Terminal, we noticed that after trying to set the interface mode to static:

` set mode static`

As result the cli hangs, the connection dies and afterwards the FGT becomes unavailable and inaccessible.
 
So, somehow this is what is causing the issue, we believe.

We would like to maybe test with the new image, do you have any thoughts on this ? Please let us know when you have added the image :)

Thank you very much for your assistance on this!






`

**Comment by liquid-cloud** [comment]
Hello,

The issue was caused by incorrect subnetting on our side, I am closing the issue, thanks for your help.
