### ISSUE TITLE
Error 412: Constraint constraints/compute.requireShieldedVm

### ISSUE THREAD

**Issue by wassimMG** [fortinet/fortigate-terraform-deploy#34]
Hello,

Trying with the gcp template 6.2.5 and got this error when it comes to vm deployment :

google_compute_instance.default: Creating...

Error: Error creating instance: googleapi: Error 412: Constraint constraints/compute.requireShieldedVm violated for project projects/myproject. The boot disk's 'initialize_params.source_image' field specifies a non-Shielded 
image: projects/fortigcp-project-001/global/images/fortinet-fgt-625-20200831-001-w-license. See https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints for more information.
More details:
Reason: conditionNotMet, Message: Constraint constraints/compute.requireShieldedVm violated for project projects/myproject. The boot disk's 'initialize_params.source_image' field specifies a non-Shielded image: projects/fortigcp-project-001/global/images/fortinet-fgt-625-20200831-001-w-license. See https://cloud.google.com/resource-manager/docs/organization-policy/org-policy-constraints for more information.
Reason: conditionNotMet, Message: Constraint constraints/compute.vmExternalIpAccess violated for project 346696193484. Add instance projects/myproject/zones/asia-southeast1-a/instances/myforti to the constraint to use external IP with it.

can you advise please

**Comment by mobilesuitzero** [comment]
Hi,

Thanks for the comments.

Currently, fortigate image doesn't have shieldedVM enable.  Hence, that's why the first error message.

And, as for second error message, the deployment will create external IP to associate to the VM, which seems to be restricted by the organisation restriction.

In this case, please contact your organization admin to those the policy constraints modified in order to deploy.


Cheers

**Comment by wassimMG** [comment]
Hi,

Thanks for reply.
And for shieldedVM does it mean I have to change something to enable it or another constraint like for the external IP?

**Comment by mobilesuitzero** [comment]
Hi,

Thanks for the reply.

You would need to change those constraint from organisation policy.   

One is constraints/compute.requireShieldedVm and the other one is constraints/compute.vmExternalIpAccess.

Cheers

**Comment by wassimMG** [comment]
Thanks

**Comment by mobilesuitzero** [comment]
Close this issue as it's more of a gcp related setting.
