### ISSUE TITLE
balance virtual ip

### ISSUE THREAD

**Issue by dmartinezrubio** [fortinet/fortigate-terraform-deploy#5]
Hello, I deployed it but when I power off Firewall-A, external ip didn't change to firewall-b

**Comment by mobilesuitzero** [comment]
Hi,

Which script did you used to deployed the Firewall-A/B?

Cheers

**Comment by dmartinezrubio** [comment]
I used gcp 6.2 ha

Enviado desde mi iPhone

**Comment by mobilesuitzero** [comment]
Hi,

external-ip move is base on what is configured in the sdn.

config system sdn-connector
    edit "gcp"
        set type gcp
        set ha-status enable
        config external-ip
            edit "<your cluster ip name>"          
            next
        end

Please check if the cluster ip name matches and also the instance has permission to move that cluster ip.

Also, you can check the what is moved on the Firewall-B during fail over with the following commands on the CLI.

diag debug enable
diag debug application gcpd -1


Cheers

**Comment by dmartinezrubio** [comment]
Ok, I'm going to review it.
I have more doubts. Both external ip for every FW (not the cluster ip) are
ephemeral. aren't they?
Are there any way to fix them to static?

**Comment by dmartinezrubio** [comment]
Also the cluster is deployed fine.
Fw-A is the master (priority 255) and FW-B slave (priority 100).
When I power off FW-A all works fine (fw-b is the new master).
But when I start again fw-a, fw-b follows as master of the cluster.

That is the log in fw-a:

"

master # diag debug application gcpd -1
--
Debug messages will be on for 30 minutes.
 
master # gcpd sdn connector gcp prepare to update
gcpd running in slave mode, won't update
gcpd reap child pid: 303
gcpd sdn connector gcp prepare to update
gcpd running in slave mode, won't update
gcpd reap child pid: 316
gcpd sdn connector gcp prepare to update
gcpd running in slave mode, won't update
gcpd reap child pid: 327

""

FW-B:

slave # GCP guest environment update
GCP update done
gcpd sdn connector gcp prepare to update
gcpd sdn connector gcp start updating
gcpd api url: https://www.googleapis.com/compute/v1/projects/comunicaciones-249609/zones
host:www.googleapis.com:443:172.217.18.106
gcpd api result:200
host:www.googleapis.com:443:172.217.18.106
gcpd sdn connector gcp get instance list successfully
gcpd api url: https://container.googleapis.com/v1/projects/comunicaciones-249609/locations/-/clusters
host:container.googleapis.com:443:216.58.210.10
gcpd api result:200
gcpd didn't find any GKE cluster
gcpd sdn connector gcp list GKE cluster failed
gcpd sdn connector gcp start updating IP addresses
gcpd sdn connector gcp finish updating IP addresses
gcpd reap child pid: 737
GCP guest environment update
GCP update done
gcpd sdn connector gcp prepare to update
gcpd sdn connector gcp start updating
gcpd api url: https://www.googleapis.com/compute/v1/projects/comunicaciones-249609/zones
host:www.googleapis.com:443:172.217.18.106
gcpd api result:200
host:www.googleapis.com:443:172.217.18.106
gcpd sdn connector gcp get instance list successfully
gcpd api url: https://container.googleapis.com/v1/projects/comunicaciones-249609/locations/-/clusters
host:container.googleapis.com:443:172.217.23.170
gcpd api result:200
gcpd didn't find any GKE cluster
gcpd sdn connector gcp list GKE cluster failed
gcpd sdn connector gcp start updating IP addresses
gcpd sdn connector gcp finish updating IP addresses
gcpd reap child pid: 748
GCP guest environment update
GCP update done

How can I force that allways master would be FW-A?

**Comment by mobilesuitzero** [comment]
Hi,

Yes.  The public ip are ephemeral by default.  User can convert that to static afterwards.

As for the enforce the master always on FW-A.

Can try change the override setting.

Here is for your reference.
https://help.fortinet.com/fos50hlp/56/Content/FortiOS/fortigate-high-availability/HA_FGCP_override.htm#:~:text=To%20enable%20override%20%2C%20connect%20to,always%20be%20the%20primary%20unit.


Cheers

**Comment by dmartinezrubio** [comment]
How it would be to change from ephimeral to static? I didn't find the command in terraform

**Comment by mobilesuitzero** [comment]
Hi,

You would need to add couple extra line for the static 

resource "google_compute_address" "static" {
}

And, then reference it in the network_interface

Another method is to manually change it from the gcp console.

Cheers

**Comment by dmartinezrubio** [comment]
Hi again.
I received this error when I tried to deployed it both firewall with 8 nics
(not 4).

Error: Error creating instance: googleapi: Error 400: Invalid value for
field 'resource.networkInterfaces': ''. Too many network interfaces. The
maximum number of network interfaces allowed for this machine type is 4.,
invalid

The machine "n1-standard-4" has a maximum of 8 nics.

Any suggestions?

I modify vars, main, master&slave adding all subnets and ports
