### ISSUE TITLE
Fail deploy ha 6.2

### ISSUE THREAD

**Issue by dmartinezrubio** [fortinet/fortigate-terraform-deploy#6]
Hello, when I deploy with terraform the solution, all the vpc, subnets, etc...it was deployed but I had this fail:

"Error: Error launching source instance: InvalidParameterValue: Value (arn:aws:iam::084053122642:role/rol_ha_fortinet) for parameter iamInstanceProfile.name is invalid. Invalid IAM Instance Profile name
        status code: 400, request id: e178084c-fb0d-4663-ace6-14f43790e3da"

Reviewing the doc, I had to create a role with this permission:

"{

"Version": "2012-10-17",

"Statement": [

{

"Action": [

"ec2:Describe*",

"ec2:AssociateAddress",

"ec2:AssignPrivateIpAddresses",

"ec2:UnassignPrivateIpAddresses",

"ec2:ReplaceRoute"

],

"Resource": "*",

"Effect": "Allow"

}

]

}"

I did it, I created that role with a associate policy with that permission (also I tried with full permission)

Can you help me?

Regards

**Comment by dmartinezrubio** [comment]
Also I tried succesfully to create an ec2 with that role via console

**Comment by mobilesuitzero** [comment]
Hi,

Just replace the variable iam with your new iam role name that created.

variable "iam" {
  default = "<your new iam role name>"
}

And, that should work.


Cheers

**Comment by dmartinezrubio** [comment]
It was the first I did:

// IAM role that has proper permission for HA
// Refer to https://docs.fortinet.com/vm/aws/fortigate/6.2/aws-cookbook/6.2.0/229470/deploying-fortigate-vm-active-passive-ha-aws-between-multiple-zones
variable "iam" {
  default = "arn:aws:iam::084053122642:role/rol_ha_fortinet"
}

**Comment by mobilesuitzero** [comment]
Try 
variable "iam" {
default = "rol_ha_fortinet"
}
Cheers
