### ISSUE TITLE
aws fail deploy 6.4 ha with TGW

### ISSUE THREAD

**Issue by dmartinezrubio** [fortinet/fortigate-terraform-deploy#7]
Error: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'taskcat' does not exist
        status code: 400, request id: c59a3ab1-1f54-4fa9-937d-c58e8b55017a

Error: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'taskcat' does not exist
        status code: 400, request id: 5189029b-f7fe-4d9e-ad7e-245ffd2a03b7

Error: Error launching source instance: InvalidKeyPair.NotFound: The key pair 'taskcat' does not exist
        status code: 400, request id: 35e76ce6-e6c0-4606-9759-918e8bf89375

Error: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=2wqkpek696qhdeo7lbbjncqli
        status code: 401, request id: 6abef3ab-acc3-4155-9085-77085c1aae20

Error: Error launching source instance: OptInRequired: In order to use this AWS Marketplace product you need to accept terms and subscribe. To do so please visit https://aws.amazon.com/marketplace/pp?sku=2wqkpek696qhdeo7lbbjncqli
        status code: 401, request id: fef34c55-6f02-4cbf-b726-a6bb82d3346b

**Comment by mobilesuitzero** [comment]
Please change the ssh key pair in the variable to use the key pair that you have in your account.

variable "keypair" {
  description = "Provide a keypair for accessing the FortiGate instances"
  default     = "taskcat"   <---  change to the ssh key that exist in your account.
}
