### ISSUE TITLE
interface, route, and vip config in aws/6.2/multi-az is incorrect

### ISSUE THREAD

**Issue by erichrockman** [fortinet/fortigate-terraform-deploy#9]
The config-active.conf is missing the vdom-exception cli statements that restrict the synchronization of interface, static route, and vip config.

https://github.com/fortinet/fortigate-terraform-deploy/blob/main/aws/6.2/ha/config-active.conf and https://github.com/fortinet/fortigate-terraform-deploy/blob/main/aws/6.2/ha/config-passive.conf

config system vdom-exception
edit 1
set object system.interface
next
edit 2
set object router.static
next
edit 3
set object firewall.vip
next
end

**Comment by mobilesuitzero** [comment]
Thanks.

Will add those exception.

Cheers

**Comment by Joel-Cripps** [comment]
changes are present here: https://github.com/fortinet/fortigate-terraform-deploy/blob/main/aws/6.2/ha/config-active.conf
