### ISSUE TITLE
EU-WEST-1 AMI is not recognised anymore

### ISSUE THREAD

**Issue by x4141** [fortinet/fortigate-terraform-deploy#94]
EU-WEST-1 AMI is not recognised anymore.

When using the EU-WEST-1 AMI you get the following error: 

│ Error: error collecting instance settings: empty result
│
│   with aws_instance.fgtactive,
│   on instance-active.tf line 58, in resource "aws_instance" "fgtactive":
│   58: resource "aws_instance" "fgtactive" {

If you switch to a modern 7.0 AMI it passes if you remove the instance profile from the terraform resource

**Comment by mobilesuitzero** [comment]
Hi,

Which folder are you using for the deployment?

The AMIs that are defined for the eu-west-1 in the variables.tf file

ami-0788ecffa9d575080  <---  FortiGate-VM64-AWSONDEMAND build0304 (7.0.5) GA
ami-0c2293c1c0708af3d  <--- FortiGate-VM64-AWS build0304 (7.0.5) GA


Can you double check if you are able to see those ami from your EC2->Images->AMIs, and search for those two AMIs.  It should still be able to find it.


Cheers
