### ISSUE TITLE
name changed in 7.x from master --> primary

### ISSUE THREAD

**Issue by hteibler** [fortinet/fortigate-terraform-deploy#99]
cause of name change in 7.x from master --> primary the config templates are wrong
should be:
AWS-FGTA # show system auto-scale 
config system auto-scale
    set status enable
    set role primary
    set sync-interface "port1"

AWS-FGTB # show system auto-scale 
config system auto-scale
    set status enable
    set sync-interface "port1"
    set primary-ip 10.1.0.10

**Comment by mobilesuitzero** [comment]
thanks.  will update that.

**Comment by mobilesuitzero** [comment]
fixed in the latest pr.
